name: awsome_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/wlopLogin.jpg
  - assets/sekiro.jpg
  - assets/wlopAccountPicture.jpg
  - assets/wlopDrawerHeaderBackground.jpg
  - assets/wlopPlaceHolderImage.jpg
  - assets/wallpaperHD.jpg
  - assets/divisionMaps/barisalDivisionMap.png
  - assets/divisionMaps/chittagongDivisionMap.png
  - assets/divisionMaps/dhakaDivisionMap.png
  - assets/divisionMaps/khulnaDivisionMap.png
  - assets/divisionMaps/mymensinghDivisionMap.png
  - assets/divisionMaps/rajshahiDivisionMap.png
  - assets/divisionMaps/rangpurDivisionMap.png
  - assets/divisionMaps/sylhetDivisionMap.png
  - assets/barisal/barisal0.jpg
  - assets/barisal/barisal1.jpg
  - assets/barisal/barisal2.jpg
  - assets/barisal/barisal3.jpg
  - assets/barisal/barisal4.jpg
  - assets/barisal/barisal5.jpg
  - assets/barisal/barisal6.jpg
  - assets/barisal/barisal7.jpg
  - assets/barisal/barisal9.jpg
  - assets/barisal/barisal10.jpg
  - assets/comilla/comilla0.jpg
  - assets/comilla/comilla1.jpg
  - assets/comilla/comilla2.jpg
  - assets/comilla/comilla3.jpg
  - assets/comilla/comilla4.jpg
  - assets/comilla/comilla5.jpg
  - assets/comilla/comilla6.jpg
  - assets/comilla/comilla7.jpg
  - assets/comilla/comilla8.jpg
  - assets/comilla/comilla9.jpg
  - assets/comilla/comilla10.jpg
  - assets/comilla/comilla11.jpg
  - assets/comilla/comilla12.jpg
  - assets/comilla/comilla13.jpg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
